### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by knoxx093** [Lencerf/vscode-beancount#14]
```Activating extension 'Lencerf.beancount' failed:  ENOENT: no such file or directory, uv_chdir```

I receive a few instances of the above message in the developer console whenever opening a .bean file.
I have no idea if this is user error or a problem with the plugin.
Here is the accompanying stacktrace.

```[Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, uv_chdir
    at process.chdir (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\polyfills.js:21:9)
    at process.chdir (C:\Users\Name\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.1071\node_modules\graceful-fs\polyfills.js:21:9)
    at process.chdir (C:\Users\Name\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.1071\node_modules\read-last-lines\node_modules\graceful-fs\polyfills.js:21:9)
    at Extension.refreshData (C:\Users\Name\.vscode\extensions\lencerf.beancount-0.3.0\out\extension.js:47:23)
    at activate (C:\Users\Name\.vscode\extensions\lencerf.beancount-0.3.0\out\extension.js:22:15)
    at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:759:329)
    at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:759:6)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:758:173
    at <anonymous>```

**Comment by knoxx093** [comment]
I was able to fix the problem by replacing instances of 
`vscode.workspace.workspaceFolders[0].uri.path`
with 
`vscode.workspace.workspaceFolders[0].uri.fsPath.replace("\\", "/")`

**Comment by Lencerf** [comment]
@knoxx093 Thanks! I tried fixing this problem. Can you please try the version in the attachment and see if there are any problems?
[beancount-0.3.1.vsix.zip](https://github.com/Lencerf/vscode-beancount/files/2719090/beancount-0.3.1.vsix.zip)

**Comment by knoxx093** [comment]
Yea that seems to work fine
